CREATE TABLE IF NOT EXISTS [Story] (
    [id] INTEGER PRIMARY KEY AUTOINCREMENT,
    [tbID] INTEGER NOT NULL UNIQUE,
    [title] TEXT NOT NULL,
    [summary] TEXT NOT NULL,
    [phase] TEXT NOT NULL,
    [wordCount] INTEGER NOT NULL,
    [lastUpdated] INTEGER NOT NULL,
    [url] TEXT UNIQUE,
    [isActive] BOOLEAN NOT NULL DEFAULT FALSE
);

CREATE TABLE IF NOT EXISTS [Lore] (
    [id] INTEGER PRIMARY KEY AUTOINCREMENT,
    [key] TEXT NOT NULL UNIQUE,
    [name] TEXT NOT NULL,
    [type] TEXT NOT NULL,
    [iconUrl] TEXT,
    [content] TEXT NOT NULL,
    [isActive] BOOLEAN NOT NULL DEFAULT FALSE
);

CREATE TABLE IF NOT EXISTS [Lore4Story] (
    [id] INTEGER PRIMARY KEY AUTOINCREMENT,
    [storyID] INTEGER NOT NULL,
    [loreID] INTEGER NOT NULL,

    FOREIGN KEY ([storyID]) REFERENCES [Story]([id]) ON DELETE CASCADE,
    FOREIGN KEY ([loreID]) REFERENCES [Lore]([id]) ON DELETE CASCADE,
    UNIQUE([storyID], [loreID]) ON CONFLICT IGNORE
);

CREATE TABLE IF NOT EXISTS [Tag] (
    [id] INTEGER PRIMARY KEY AUTOINCREMENT,
    [name] TEXT NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS [Tag4Story] (
    [id] INTEGER PRIMARY KEY AUTOINCREMENT,
    [storyID] INTEGER NOT NULL,
    [tagID] INTEGER NOT NULL,

    FOREIGN KEY ([storyID]) REFERENCES [Story]([id]) ON DELETE CASCADE,
    FOREIGN KEY ([tagID]) REFERENCES [Tag]([id]) ON DELETE CASCADE,
    UNIQUE([storyID], [tagID]) ON CONFLICT IGNORE
);

CREATE TABLE IF NOT EXISTS [Sync] (
    [id] INTEGER PRIMARY KEY AUTOINCREMENT,
    [key] TEXT NOT NULL UNIQUE,
    [lastSuccess] INTEGER,
    [lastAttempt] INTEGER,
    [error] TEXT,
    [interval] INTEGER,
    [isActive] BOOLEAN NOT NULL DEFAULT FALSE
);

CREATE TABLE IF NOT EXISTS [User] (
    [id] INTEGER PRIMARY KEY AUTOINCREMENT,
    [username] TEXT NOT NULL UNIQUE,
    [passwordHash] TEXT NOT NULL,
    [passwordSalt] TEXT NOT NULL,
    [isAdmin] BOOLEAN NOT NULL DEFAULT FALSE,
    [isActive] BOOLEAN NOT NULL DEFAULT FALSE
);
